// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class ServerModuleBindings
    {
        readonly ICloudCodeService k_Service;
        public ServerModuleBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> SaveGameState()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "ServerModule",
                "SaveGameState",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> GetGameState()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "ServerModule",
                "GetGameState",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
